TARGET_BOARD_DERIVATIVE_SUFFIX := _gy_qmaa

# Inherit from the base product
include device/qcom/gen4_gvm_gy/gen4_gvm_gy.mk

LOCAL_PATH := $(call my-dir)

PRODUCT_NAME := gen4_gvm_gy_qmaa
PRODUCT_DEVICE := gen4_gvm_gy_qmaa
PRODUCT_BRAND := qti
PRODUCT_MODEL := gen4_gvm_gy_qmaa for arm64

TARGET_USES_QMAA := true
TARGET_USES_QMAA_OVERRIDE_AUDIO   := false
TARGET_USES_QMAA_OVERRIDE_DISPLAY := false
#TARGET_USES_QMAA_OVERRIDE_FASTCV  := true
TARGET_USES_QMAA_OVERRIDE_GFX := false
TARGET_USES_QMAA_OVERRIDE_KMGK := false
#TARGET_USES_QMAA_OVERRIDE_SECUREMSM_TESTS := false
#TARGET_USES_QMAA_OVERRIDE_SMCINVOKE := false
TARGET_USES_QMAA_OVERRIDE_VIDEO   := false
#TARGET_USES_QMAA_OVERRIDE_USB := false
#TARGET_USES_QMAA_OVERRIDE_WLAN    := false
#TARGET_KERNEL_DLKM_SECURE_MSM_OVERRIDE := false
#TARGET_KERNEL_DLKM_SECUREMSM_QTEE_OVERRIDE := false
#TARGET_KERNEL_DLKM_DISABLE := true
TARGET_KERNEL_DLKM_DISPLAY_OVERRIDE := false
TARGET_KERNEL_DLKM_AUDIO_OVERRIDE := false
TARGET_KERNEL_DLKM_WLAN_OVERRIDE := false
#TARGET_USES_QMAA_OVERRIDE_HSI2S := false
#TARGET_KERNEL_DLKM_VIDEO_OVERRIDE := false
#TARGET_KERNEL_DLKM_SYNX_OVERRIDE := false
TARGET_DISABLE_DISPLAY_DLKM := true
#TARGET_USES_QMAA_OVERRIDE_PLATFORM_KERNEL := false

#TARGET_OUT_INTERMEDIATES := out/target/product/$(PRODUCT_NAME)/obj
#$(TARGET_OUT_INTERMEDIATES)/KERNEL_OBJ/usr:
#	mkdir -p $(TARGET_OUT_INTERMEDIATES)/KERNEL_OBJ/usr

$(call inherit-product-if-exists, vendor/qcom/defs/product-defs/system/*.mk)
$(call inherit-product-if-exists, vendor/qcom/defs/product-defs/vendor/*.mk)
